### ISSUE TITLE
price calculation is wack

### ISSUE THREAD

**Issue by Peletic** [JackTYM/SkyblockFlipper#2]
maybe the reason is because you're searching for the exact star the item is?- if so probably a setting to remove the stars would be a good piece of qol

(price calculation in the actual flipping i mean)

**Comment by JackTYM** [comment]
yep, currently working on switching apis right now. Switching to Moulberry’s NEU api rather than Hypixel as it handles things better

**Comment by JackTYM** [comment]
Fixed Issues with the price calculation command and how the prices are handled.
